"""init_modelos_base

Revision ID: 6a65fa2dd1f5
Revises: 
Create Date: 2026-03-23 12:24:24.649561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a65fa2dd1f5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complemento_dep',
    sa.Column('codigo', sa.String(length=2), nullable=False),
    sa.Column('nombre_departamento', sa.String(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('codigo', name=op.f('pk_complemento_dep')),
    schema='rrhh'
    )
    op.create_table('departamento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('id_padre', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_padre'], ['rrhh.departamento.id'], name=op.f('fk_departamento_id_padre_departamento'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departamento')),
    sa.UniqueConstraint('codigo', name=op.f('uq_departamento_codigo')),
    schema='rrhh'
    )
    op.create_table('rol',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rol')),
    sa.UniqueConstraint('nombre', name=op.f('uq_rol_nombre')),
    schema='rrhh'
    )
    op.create_table('cargo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('es_cargo_confianza', sa.Boolean(), nullable=False, comment='TRUE = exento de marcar huella biométrica'),
    sa.Column('id_departamento', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_departamento'], ['rrhh.departamento.id'], name=op.f('fk_cargo_id_departamento_departamento'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cargo')),
    sa.UniqueConstraint('codigo', name=op.f('uq_cargo_codigo')),
    schema='rrhh'
    )
    op.create_table('empleado',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ci_numero', sa.String(length=20), nullable=False),
    sa.Column('complemento_dep', sa.String(length=2), nullable=False),
    sa.Column('ci_sufijo_homonimo', sa.String(length=10), nullable=True, comment='Sufijo para homónimos SEGIP'),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('genero', sa.Enum('masculino', 'femenino', 'otro', name='genero_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('activo', 'baja', 'suspendido', name='estado_empleado_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id_cargo', sa.Integer(), nullable=False),
    sa.Column('id_departamento', sa.Integer(), nullable=False),
    sa.Column('salario_base', sa.Numeric(precision=12, scale=2), nullable=False, comment='Salario vigente en Bs. - se actualiza desde ajuste_salarial'),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('foto_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['complemento_dep'], ['rrhh.complemento_dep.codigo'], name=op.f('fk_empleado_complemento_dep_complemento_dep'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_cargo'], ['rrhh.cargo.id'], name=op.f('fk_empleado_id_cargo_cargo'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_departamento'], ['rrhh.departamento.id'], name=op.f('fk_empleado_id_departamento_departamento'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_empleado')),
    schema='rrhh'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('empleado', schema='rrhh')
    op.drop_table('cargo', schema='rrhh')
    op.drop_table('rol', schema='rrhh')
    op.drop_table('departamento', schema='rrhh')
    op.drop_table('complemento_dep', schema='rrhh')
    # ### end Alembic commands ###
