"""semana5_modulo_marcaciones

Revision ID: f3b939aeeb88
Revises: 178589bf4bd3
Create Date: 2026-04-06 12:10:38.069459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3b939aeeb88'
down_revision: Union[str, None] = '178589bf4bd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archivo_excel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=False),
    sa.Column('ruta_storage', sa.String(length=255), nullable=False, comment='Ruta física del archivo en el servidor'),
    sa.Column('id_subido_por', sa.Integer(), nullable=True, comment='SET NULL: preservar log aunque el usuario sea eliminado'),
    sa.Column('fecha_subida', sa.TIMESTAMP(), nullable=False),
    sa.Column('estado_procesamiento', sa.Enum('pendiente', 'procesando', 'completado', 'error', name='estado_procesamiento_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('total_filas', sa.Integer(), nullable=True),
    sa.Column('filas_procesadas', sa.Integer(), nullable=True),
    sa.Column('filas_con_error', sa.Integer(), nullable=True),
    sa.Column('log_errores', sa.Text(), nullable=True, comment='JSON con detalle de filas problemáticas'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_subido_por'], ['rrhh.usuario.id'], name=op.f('fk_archivo_excel_id_subido_por_usuario'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_archivo_excel')),
    schema='rrhh'
    )
    op.create_table('marcacion',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_empleado', sa.Integer(), nullable=False),
    sa.Column('fecha_hora_marcacion', sa.TIMESTAMP(), nullable=False, comment='Timestamp exacto de la marcación'),
    sa.Column('tipo_marcacion', sa.Enum('ENTRADA', 'SALIDA', name='tipo_marcacion_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('origen_dato', sa.Enum('Excel', 'API_Biometrico', 'Manual', name='origen_dato_enum', native_enum=False, create_constraint=True), nullable=False, comment='Clave de transición Fase1→Fase2'),
    sa.Column('id_archivo_excel', sa.Integer(), nullable=True, comment='NULL si origen no es Excel'),
    sa.Column('id_marcacion_par', sa.BigInteger(), nullable=True, comment='FK autorreferencial: ENTRADA↔SALIDA. SET NULL: si se elimina una, la otra queda huérfana'),
    sa.Column('es_duplicada', sa.Boolean(), nullable=False, comment='TRUE = dos marcaciones del mismo tipo consecutivas'),
    sa.Column('es_huerfana', sa.Boolean(), nullable=False, comment='TRUE = no tiene pareja (entrada sin salida o viceversa)'),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_archivo_excel'], ['rrhh.archivo_excel.id'], name=op.f('fk_marcacion_id_archivo_excel_archivo_excel'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_empleado'], ['rrhh.empleado.id'], name=op.f('fk_marcacion_id_empleado_empleado'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_marcacion_par'], ['rrhh.marcacion.id'], name=op.f('fk_marcacion_id_marcacion_par_marcacion'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_marcacion')),
    schema='rrhh'
    )
    op.create_index('idx_marcacion_empleado_fecha', 'marcacion', ['id_empleado', 'fecha_hora_marcacion'], unique=False, schema='rrhh')
    op.create_table('incidencia_marcacion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_marcacion', sa.BigInteger(), nullable=False),
    sa.Column('tipo_incidencia', sa.Enum('marcacion_huerfana', 'marcacion_duplicada', 'horario_irregular', name='tipo_incidencia_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('estado_resolucion', sa.Enum('pendiente', 'revisado', 'resuelto', 'descartado', name='estado_resolucion_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('evidencia_url', sa.String(length=255), nullable=True, comment='URL de documento escaneado o correo que respalda la resolución'),
    sa.Column('descripcion_resolucion', sa.Text(), nullable=True),
    sa.Column('id_resuelto_por', sa.Integer(), nullable=True, comment='SET NULL: preservar historial aunque el usuario sea eliminado'),
    sa.Column('fecha_resolucion', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_marcacion'], ['rrhh.marcacion.id'], name=op.f('fk_incidencia_marcacion_id_marcacion_marcacion'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_resuelto_por'], ['rrhh.usuario.id'], name=op.f('fk_incidencia_marcacion_id_resuelto_por_usuario'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidencia_marcacion')),
    sa.UniqueConstraint('id_marcacion', name=op.f('uq_incidencia_marcacion_id_marcacion')),
    schema='rrhh'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incidencia_marcacion', schema='rrhh')
    op.drop_index('idx_marcacion_empleado_fecha', table_name='marcacion', schema='rrhh')
    op.drop_table('marcacion', schema='rrhh')
    op.drop_table('archivo_excel', schema='rrhh')
    # ### end Alembic commands ###
